language: node_js

dist: trusty
sudo: true

addons:
  chrome: stable

services:
  - docker

node_js:
  - "10"

before_install:
  # Install recent Yarn for workspaces support
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  # Mute Yarn's progress
  - yarn config set no-progress

  # Use greenkeeper-lockfile >= 2.0 for monorepo support
  #  - yarn global add greenkeeper-lockfile@2

before_script:
  #  - greenkeeper-lockfile-update

  # Check we lint and compile correctly first
  - yarn run lint
  - yarn run license-check
  - yarn run compile

after_script:
  #  - greenkeeper-lockfile-upload

script:
  - yarn run $COMMAND

env:
  global:

  matrix:
    - COMMAND=test:ci
    - COMMAND=e2e:ci

branches:
  only:
  - master
  - /^greenkeeper/.*$/

cache: yarn
