language: node_js

dist: trusty
sudo: true

addons:
  chrome: stable

services:
  - docker

node_js:
  - "10"

before_install:
  - yarn config set no-progress

  # Use greenkeeper-lockfile >= 2.0 for monorepo support
  #  - yarn global add greenkeeper-lockfile@2

before_script:
  #  - greenkeeper-lockfile-update

  # Check we lint and compile correctly first
  - yarn run lint
  - yarn run license-check
  - yarn run compile

after_script:
  #  - greenkeeper-lockfile-upload

after_success:
  - nyc report --reporter=text-lcov > coverage.lcov
  - npx codecov

script: yarn run $COMMAND

env:
  global:

  matrix:
  - DATABASE=couchdb:latest COMMAND=test

branches:
  only:
  - master
  - /^greenkeeper/.*$/

cache: yarn
