language: node_js

sudo: false

services:
  - couchdb

node_js:
  - "6"
  - "8"

before_script:
  # Check we build and lint correctly first
  - npm run build
  - npm run lint

script: npm run test

branches:
  only:
  - master
  - /^greenkeeper/.*$/
